// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: ai/v1/agent.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAIAgentChat = "/api.ai.v1.AIAgent/Chat"

type AIAgentHTTPServer interface {
	// Chat 与 AI 聊天
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
}

func RegisterAIAgentHTTPServer(s *http.Server, srv AIAgentHTTPServer) {
	r := s.Route("/")
	r.POST("/ai/v1/chat", _AIAgent_Chat0_HTTP_Handler(srv))
}

func _AIAgent_Chat0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Chat(ctx, req.(*ChatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatReply)
		return ctx.Result(200, reply)
	}
}

type AIAgentHTTPClient interface {
	Chat(ctx context.Context, req *ChatRequest, opts ...http.CallOption) (rsp *ChatReply, err error)
}

type AIAgentHTTPClientImpl struct {
	cc *http.Client
}

func NewAIAgentHTTPClient(client *http.Client) AIAgentHTTPClient {
	return &AIAgentHTTPClientImpl{client}
}

func (c *AIAgentHTTPClientImpl) Chat(ctx context.Context, in *ChatRequest, opts ...http.CallOption) (*ChatReply, error) {
	var out ChatReply
	pattern := "/ai/v1/chat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIAgentChat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
