// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/ai/v1/agent.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 聊天请求
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Context       []string               `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"` // 对话上下文
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_ai_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatRequest) GetContext() []string {
	if x != nil {
		return x.Context
	}
	return nil
}

// 聊天回复
type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_api_ai_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_api_ai_v1_agent_proto protoreflect.FileDescriptor

const file_api_ai_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/ai/v1/agent.proto\x12\tapi.ai.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"H\n" +
	"\vChatRequest\x12\x1f\n" +
	"\x06prompt\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06prompt\x12\x18\n" +
	"\acontext\x18\x02 \x03(\tR\acontext\"'\n" +
	"\tChatReply\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2W\n" +
	"\aAIAgent\x12L\n" +
	"\x04Chat\x12\x16.api.ai.v1.ChatRequest\x1a\x14.api.ai.v1.ChatReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/ai/v1/chatB\"\n" +
	"\tapi.ai.v1P\x01Z\x13review/api/ai/v1;v1b\x06proto3"

var (
	file_api_ai_v1_agent_proto_rawDescOnce sync.Once
	file_api_ai_v1_agent_proto_rawDescData []byte
)

func file_api_ai_v1_agent_proto_rawDescGZIP() []byte {
	file_api_ai_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_ai_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_v1_agent_proto_rawDesc), len(file_api_ai_v1_agent_proto_rawDesc)))
	})
	return file_api_ai_v1_agent_proto_rawDescData
}

var file_api_ai_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ai_v1_agent_proto_goTypes = []any{
	(*ChatRequest)(nil), // 0: api.ai.v1.ChatRequest
	(*ChatReply)(nil),   // 1: api.ai.v1.ChatReply
}
var file_api_ai_v1_agent_proto_depIdxs = []int32{
	0, // 0: api.ai.v1.AIAgent.Chat:input_type -> api.ai.v1.ChatRequest
	1, // 1: api.ai.v1.AIAgent.Chat:output_type -> api.ai.v1.ChatReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ai_v1_agent_proto_init() }
func file_api_ai_v1_agent_proto_init() {
	if File_api_ai_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_v1_agent_proto_rawDesc), len(file_api_ai_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ai_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_ai_v1_agent_proto_depIdxs,
		MessageInfos:      file_api_ai_v1_agent_proto_msgTypes,
	}.Build()
	File_api_ai_v1_agent_proto = out.File
	file_api_ai_v1_agent_proto_goTypes = nil
	file_api_ai_v1_agent_proto_depIdxs = nil
}
